version: '3.3'
services:
    graph_database:
      image: neo4j
      container_name: neo4j_db
      ports:
        - 7474:7474
        - 7687:7687
      environment:
        - NEO4J_AUTH=neo4j/test
      volumes:
        - neo4j_data:/data

volumes:
  neo4j_data:
    driver: local
